# vim: set ft=ansible
# site.yml
---

- hosts: rhel_mirrors
  become: true
  vars_files:
    - "./vars/main.yml"
    - ~/.ansible/vars/rhel_local_mirrors_vars.yml
  vars:
    sudo_defaults:
      - defaults: '!requiretty'
  tasks:
    - include: test_rhel_register.yml
      when: subscribe_rhn|bool == True
      tags:
        - rhel_register

    - include: test_prepare_system.yml
      tags:
        - prepare_system
