# vim: set ft=ansible
# site.yml
---

- hosts: local_mirrors
  become: true
  vars_files:
    - "./vars/main.yml"
  roles:
    - role: geerlingguy.nginx
      tags:
        - install_nginx
  tasks:
    - include_tasks: test_rhel_register.yml
      tags:
        - rhel_register

    - include_tasks: test_prepare_system.yml
      tags:
        - prepare_system
    - include_tasks: test_create_mirror_repos.yml
      tags:
        - create_mirrors
    - include_tasks: test_create_local_repos.yml
      tags:
        - create_local
